---
title: "OnDemand_Patronage"
author: "Tim Kelso"
date: "16/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
library(tidyverse)
library(lubridate)
```

``` {r import_wrangle}
OnDemandPilot_Patronage <- read_csv("../data_raw/on_demand_pilot_patronage_2021-04.csv")


OnDemandPilot_Patronage <- OnDemandPilot_Patronage %>% 
  rename(PilotName = `Contract Name`) %>% 
  pivot_longer(cols = `Oct-17`:last_col(), 
               names_to = "Date",
               values_to = "Trips") %>% 
  mutate(Date = dmy(paste0("01-", Date))) #convert to date
```

``` {r plot}
Bykko_Patronage_Plot <- OnDemandPilot_Patronage %>%
  filter(PilotName == "Bykko - Newcastle (Pilot)") %>% 
  ggplot(aes(x = Date, y = Trips)) +
  geom_point(aes(color = PilotName))+
  geom_line(aes(color = PilotName)) +
  scale_x_date(date_labels = "%b-%Y") + #TODO: add more breaks in x-axis to highlight peak/trough times
  theme_classic() +
  labs(caption = "Source: TfNSW Open Data Hub, accessed 3/5/2021")
ggsave("../images/BykkoPlot.png")

#TODO: crystallise the question/s you want to ask
#TODO: investigate if there are any other bikeshare pilots in this list? eg. LiveBetter?
#TODO: investigate if there are any other pilots nearby that might be worth comparing?
```